---
- name: Deploy WAR to Tomcat from Nexus
  hosts: app1
  become: yes

  vars:
    nexus_url: "http://13.51.237.106:8081"
    nexus_repo: "dobretech-repo-snap"
    group_id: "com.example"
    artifact_id: "myapp"
    version: "1.0-SNAPSHOT"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_webapps: "/opt/tomcat/latest/webapps"
    nexus_metadata_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/maven-metadata.xml"

  tasks:

    - name: Ensure Tomcat directory structure exists
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'
      loop:
        - "/opt/tomcat"
        - "/opt/tomcat/latest"
        - "{{ tomcat_webapps }}"

    - name: Create symlink to Tomcat
      file:
        src: "/opt/tomcat/apache-tomcat-9.0.89"
        dest: "/opt/tomcat/latest"
        state: link
        force: yes

    - name: Ensure webapps directory exists
      file:
        path: "{{ tomcat_webapps }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'

    - name: Query Nexus metadata to get resolved SNAPSHOT version
      uri:
        url: "{{ nexus_metadata_url }}"
        return_content: yes
      register: nexus_metadata

    - name: Parse resolved SNAPSHOT WAR version using regex
      set_fact:
        snapshot_version: "{{ (nexus_metadata.content | regex_search('<value>([^<]+)</value>', '\\1'))[0] }}"

    - name: Set resolved WAR URL and destination
      set_fact:
        resolved_war_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ snapshot_version }}.war"
        war_dest_path: "{{ tomcat_webapps }}/{{ artifact_id }}.war"

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ resolved_war_url }}"
        dest: "{{ war_dest_path }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0644'
      retries: 3
      delay: 5
      register: war_download
      until: war_download is succeeded

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: yes
