---
- name: Deploy SNAPSHOT WAR to Tomcat 11
  hosts: app1
  become: true
  vars:
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_base: /opt/tomcat-11
    app_context: newapp
    nexus_url: http://13.51.237.106:8081
    nexus_repo: dobretech-repo-snap
    group_id: com.example.myapp
    artifact_id: myapp
    version: 1.0-SNAPSHOT

  tasks:
    - name: Ensure webapps directory exists
      file:
        path: "{{ tomcat_base }}/webapps"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0755'

    - name: Get maven-metadata.xml
      uri:
        url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/maven-metadata.xml"
        return_content: yes
      register: nexus_metadata

    - name: Parse resolved SNAPSHOT WAR version using regex
      set_fact:
        resolved_snapshot_version: "{{ nexus_metadata.content | regex_search('<value>([^<]+)</value>', '\\1') }}"

    - name: Set WAR URL and destination
      set_fact:
        war_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ resolved_snapshot_version }}.war"
        war_dest: "{{ tomcat_base }}/webapps/{{ app_context }}.war"

    - name: Download WAR file
      get_url:
        url: "{{ war_url }}"
        dest: "{{ war_dest }}"
        mode: '0644'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        enabled: yes
