---
- name: Deploy SNAPSHOT WAR to Tomcat
  hosts: app1
  become: yes

  vars:
    nexus_url: "http://13.51.237.106:8081"
    nexus_repo: "dobretech-repo-snap"
    group_id: "com.example"
    artifact_id: "myapp"
    version: "1.0-SNAPSHOT"
    dest_dir: "/opt/tomcat/webapps"
    tomcat_service: "tomcat"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Set group_path
      set_fact:
        group_path: "{{ group_id | replace('.', '/') }}"

    - name: Set artifact_base_path and metadata_url
      set_fact:
        artifact_base_path: "{{ group_path }}/{{ artifact_id }}/{{ version }}"
        metadata_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ artifact_base_path }}/maven-metadata.xml"

    - name: Debug metadata URL (optional)
      debug:
        msg: "{{ metadata_url }}"
