---
- name: Deploy SNAPSHOT WAR to Tomcat
  hosts: app1
  become: yes
  vars:
    nexus_url: "http://13.51.237.106:8081"
    nexus_repo: "dobretech-repo-snap"
    group_id: "com.example"
    artifact_id: "myapp"
    version: "1.0-SNAPSHOT"   # <-- SNAPSHOT
    dest_dir: "/opt/tomcat/webapps"
    tomcat_service: "tomcat"

  tasks:
    - name: Ensure Tomcat webapps directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Query Nexus maven-metadata.xml
      uri:
        url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/maven-metadata.xml"
        return_content: yes
      register: nexus_metadata

    - name: Extract SNAPSHOT resolved version (timestamp & build)
      set_fact:
        snapshot_resolved_version: "{{ nexus_metadata.content | regex_findall('>([0-9].*?\\.war)<') | first }}"
        
    - name: Debug Snapshot Version (Optional)
      debug:
        msg: "{{ snapshot_resolved_version }}"

    - name: Set final WAR download URL
      set_fact:
        war_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ snapshot_resolved_version }}"
        war_dest: "{{ dest_dir }}/{{ artifact_id }}.war"

    - name: Download resolved WAR from Nexus
      get_url:
        url: "{{ war_url }}"
        dest: "{{ war_dest }}"
        owner: tomcat
        group: tomcat
        mode: '0644'
      register: war_download

    - name: Restart Tomcat
      systemd:
        name: "{{ tomcat_service }}"
        state: restarted
      when: war_download.changed
