---
- name: Deploy SNAPSHOT WAR from Nexus to Tomcat
  hosts: app1
  become: yes
  vars:
    nexus_url: "http://13.51.237.106:8081"
    nexus_repo: "dobretech-repo-snap"
    group_id: "com.example"                 # <--- FIXED groupId
    artifact_id: "myapp"
    version: "1.0-SNAPSHOT"
    dest_dir: "/opt/tomcat/webapps"
    deploy_user: "tomcat"
    deploy_group: "tomcat"

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_group }}"
        mode: '0755'

    - name: Construct Maven metadata URL
      set_fact:
        metadata_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/maven-metadata.xml"

    - name: Debug metadata URL (optional)
      debug:
        msg: "{{ metadata_url }}"

    - name: Download maven-metadata.xml
      uri:
        url: "{{ metadata_url }}"
        method: GET
        return_content: yes
      register: nexus_metadata
      failed_when: "'<snapshotVersion>' not in nexus_metadata.content"

    - name: Extract SNAPSHOT resolved version using regex
      set_fact:
        snapshot_resolved_version: "{{ nexus_metadata.content | regex_search('<value>(.*?)</value>', '\\1') }}"

    - name: Set final WAR URL and destination
      set_fact:
        resolved_war_url: "{{ nexus_url }}/repository/{{ nexus_repo }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ snapshot_resolved_version }}.war"
        war_dest_path: "{{ dest_dir }}/{{ artifact_id }}.war"

    - name: Debug WAR URL (optional)
      debug:
        msg: "{{ resolved_war_url }}"

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ resolved_war_url }}"
        dest: "{{ war_dest_path }}"
        mode: '0644'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_group }}"
      register: war_download
      retries: 3
      delay: 5
      until: war_download is succeeded

    - name: Restart Tomcat (optional, only if you want to reload WAR)
      service:
        name: tomcat
        state: restarted
      when: war_download.changed
